### ISSUE TITLE
Pilot station

### ISSUE THREAD

**Issue by amir-arad** [starwards/starwards#1193]
widgets:
 - [ ] Systems status ( blocked by #1189 )
 - [ ] Warp controls ( blocked by #1190 )
 - [ ]  pilot radar ( blocked by #1191 )
 - [ ] Docking control ( blocked by #1192 )
 - [ ] stats: energy, heading, speed, afterburner energy
 - [ ] Armor status
 
 hotkeys: 
  - [ ] change docking mode ( blocked by #1181 )
  - [ ] set desired warp level ( blocked by #1180 )
     - key per level
     - up/down by one level
   - [ ] boost, strafe, rotation, maneuvering mode, rotation mode.
