### ISSUE TITLE
weapons station

### ISSUE THREAD

**Issue by amir-arad** [starwards/starwards#1197]
widgets:
 - [x] Systems status ( blocked by #1189 )
 - [x] tube status  ( blocked by #1194 )
 - [x] ammo status ( blocked by #1195 )
 - [x] targeting info ( blocked by #1307 )
 - tactical radar
hotkeys:
 - [x] for each tube ( blocked by #1186 )
     -  set desired ammo
     -  set desired loading status
     -  fire tube
 - [x] targeting: 
     - next / prev target
     - toggle filters: ship only, enemy only, close range only.
