### ISSUE TITLE
Complete system status widget

### ISSUE THREAD

**Issue by amir-arad** [starwards/starwards#1199]
a big table, displaying:
 - for each ship system:
   - [x] Heat level ( blocked by #1183 )
   - [x] coolant level ( blocked by #1198 )
   - [x] malfunctions (true realtime status of everything that can go wrong in each system)
   - [x] energy consumption
   - [x] overclocking level ( blocked by #1184 )
   - [x] hack level ( blocked by #1207 )
