### ISSUE TITLE
Engineering station

### ISSUE THREAD

**Issue by amir-arad** [starwards/starwards#1203]
widgets:
 - [x] Complete system status (blocked by #1199 )
 - [x] warp frequency ( blocked by #1200 )
 - [x] Armor status
 - [x] engineering control status  ( blocked by #1202 )
 - [x] stats: energy, afterburner energy + derivative
hotkeys:
 - [x] Engine calibration: toggle desired frequency up/down, set desired frequency ( blocked by #1182 )
 - [x] switch engineering control ( blocked by #1201 )
